In [7]:
%matplotlib inline
import sys
sys.path.append('/apps')
import django
django.setup()
from drivers.graph_models import TreeNode, Order, Family, graph, pickNode
from traversals.strategies import sumTrees, UniformRandomSampleForest


In [8]:
import tensorflow as tf
import GPflow as gf
import pandas as pd

In [9]:
import tensorflow as tf
import GPflow as gf
import pandas as pd
run traversals/tests.py
k = gf.kernels.Matern12(2, lengthscales=1, active_dims = [3,4])
X = pd.concat((rd[['MeanTemperature_mean','Precipitation_mean','WindSpeed_mean']],s[['Longitude','Latitude']]),axis=1)
Y = rd['Elevation_mean']
mx = X.as_matrix()
my = Y.as_matrix().reshape(16,1)
meanf = gf.mean_functions.Linear(np.ones((5,1)), np.ones(1))
m = gf.gpr.GPR(mx,my,k,mean_function=meanf)
m.optimize()
print(m)

ERROR:root:File `u'traversals/tests.py'` not found.


In [27]:
X = pd.concat((rd[['MeanTemperature_mean','Precipitation_mean','WindSpeed_mean']],s[['Longitude','Latitude']]),axis=1)

array([[ 1,  4,  1],
       [ 2, 55,  2]])

In [39]:
cc = tf.reduce_sum(x,axis=1)
print(session.run(cc))
cc = tf.reduce_sum(x,axis=0)
print(session.run(cc))
cc = tf.reduce_sum(x,axis=[0,1])
print(session.run(cc))



[ 6 59]
[ 3 59  3]
65


In [45]:
domain_of_x = tf.range(0,10,delta=0.03)
session.run(domain_of_x)

array([ 0.        ,  0.03      ,  0.06      ,  0.09      ,  0.12      ,
        0.14999999,  0.17999999,  0.20999999,  0.23999999,  0.26999998,
        0.29999998,  0.32999998,  0.35999998,  0.38999999,  0.41999999,
        0.44999999,  0.47999999,  0.50999999,  0.53999996,  0.56999993,
        0.5999999 ,  0.62999988,  0.65999985,  0.68999982,  0.71999979,
        0.74999976,  0.77999973,  0.8099997 ,  0.83999968,  0.86999965,
        0.89999962,  0.92999959,  0.95999956,  0.98999953,  1.0199995 ,
        1.04999948,  1.07999945,  1.10999942,  1.13999939,  1.16999936,
        1.19999933,  1.2299993 ,  1.25999928,  1.28999925,  1.31999922,
        1.34999919,  1.37999916,  1.40999913,  1.4399991 ,  1.46999907,
        1.49999905,  1.52999902,  1.55999899,  1.58999896,  1.61999893,
        1.6499989 ,  1.67999887,  1.70999885,  1.73999882,  1.76999879,
        1.79999876,  1.82999873,  1.8599987 ,  1.88999867,  1.91999865,
        1.94999862,  1.97999859,  2.00999856,  2.03999853,  2.06

In [46]:
tf.rank?

## correr sesión

In [36]:
session.run(cc)

array([ 3, 59,  3], dtype=int32)